# Generated by Django 5.0 on 2025-09-16 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='nom')),
                ('company', models.CharField(blank=True, max_length=200, null=True, verbose_name='entreprise')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='adresse e-mail')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='numéro de téléphone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'verbose_name': 'Débiteur',
                'verbose_name_plural': 'Débiteurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom du fournisseur')),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True, verbose_name='personne à contacter')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant')),
                ('description', models.TextField(verbose_name='description')),
                ('date_incurred', models.DateField(verbose_name='date de la dette')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='core.debtor', verbose_name='débiteur')),
            ],
            options={
                'verbose_name': 'Dette',
                'verbose_name_plural': 'Dettes',
                'ordering': ['-date_incurred'],
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant')),
                ('description', models.TextField(verbose_name='description')),
                ('date_incurred', models.DateField(verbose_name='date du crédit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='core.supplier', verbose_name='fournisseur')),
            ],
            options={
                'verbose_name': 'Crédit',
                'verbose_name_plural': 'Crédits',
                'ordering': ['-date_incurred'],
            },
        ),
    ]
