# Generated by Django 5.0 on 2025-09-16 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant payé')),
                ('date_paid', models.DateField(verbose_name='date de paiement')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.credit', verbose_name='crédit')),
            ],
            options={
                'verbose_name': 'Paiement Fournisseur',
                'verbose_name_plural': 'Paiements Fournisseurs',
                'ordering': ['-date_paid'],
            },
        ),
    ]
